return function(conf)
  local load = function(module)
    return require("CoreSystem." .. module)
  end

  load("Core")(conf)
  load("Interfaces")
  load("Exception")
  load("Math")
  load("Number")
  load("Char")
  load("String")
  load("Boolean")
  load("Delegate")
  load("Enum")
  load("Collections.EqualityComparer")
  load("Array")
  load("Span")
  load("MemoryExtensions")
  load("ReadOnlySpan")
  load("Type")
  load("Collections.List")
  load("Collections.Dictionary")
  load("Collections.Queue")
  load("Collections.HashSet")
  load("Collections.PriorityQueue")
  load("Text.StringBuilder")
end
