-- Generated by CSharp.lua Compiler
return function (path)
  return System.init({
    path = path,
    files = {
      "Delaunator",
      "Edge",
      "IEdge",
      "IPoint",
      "ITriangle",
      "IVoronoiCell",
      "Point",
      "Triangle",
      "VoronoiCell"
    },
    types = {
      "DelaunatorSharp.IEdge",
      "DelaunatorSharp.IPoint",
      "DelaunatorSharp.ITriangle",
      "DelaunatorSharp.IVoronoiCell",
      "DelaunatorSharp.Delaunator",
      "DelaunatorSharp.Edge",
      "DelaunatorSharp.Point",
      "DelaunatorSharp.Triangle",
      "DelaunatorSharp.VoronoiCell"
    }
  })
end
