-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)
  namespace.class("AvoidLocation", function (namespace)
    local __ctor__
    __ctor__ = function (this, x, y)
      this.X = x
      this.Y = y
    end
    return {
      X = 0,
      Y = 0,
      __ctor__ = __ctor__
    }
  end)
end)
