-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)
  namespace.class("BeaconSolution", function (namespace)
    local __members__, __ctor__
    __ctor__ = function (this, Strategy, Beacons, Effects)
      this.Strategy = Strategy
      this.Beacons = Beacons
      this.Effects = Effects
    end
    __members__ = function ()
      return "BeaconSolution", "Strategy", "Beacons", "Effects"
    end
    return {
      Strategy = 0,
      Effects = 0,
      base = function (out)
        return {
          System.RecordType,
          System.IEquatable_1(out.Knapcode.FactorioTools.OilField.BeaconSolution)
        }
      end,
      __members__ = __members__,
      __ctor__ = __ctor__
    }
  end)
end)
