-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.Data", function (namespace)
  namespace.class("BlueprintBook", function (namespace)
    local __ctor__
    __ctor__ = function (this)
      this.Blueprints = nil
    end
    return {
      Item = nil,
      Label = nil,
      ActiveIndex = 0,
      Version = 0,
      __ctor__ = __ctor__
    }
  end)
end)
