-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.Data", function (namespace)
  namespace.class("BlueprintRoot", function (namespace)
    return {}
  end)
end)
