-- Generated by CSharp.lua Compiler
local System = System
local KnapcodeOilField
local ListLocation
System.import(function (out)
  KnapcodeOilField = Knapcode.FactorioTools.OilField
  ListLocation = System.List(KnapcodeOilField.Location)
end)
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)
  namespace.class("BresenhamsLine", function (namespace)
    local GetPath
    GetPath = function (a, b)
      local line = ListLocation()
      local dx = math.Abs(b.X - a.X)
      local sx = (a.X < b.X) and 1 or - 1
      local dy = - 1 * math.Abs(b.Y - a.Y)
      local sy = (a.Y < b.Y) and 1 or - 1
      local error = dx + dy

      local x0 = a.X
      local y0 = a.Y

      while true do
        line:Add(KnapcodeOilField.Location(x0, y0))

        if x0 == b.X and y0 == b.Y then
          break
        end

        local e2 = 2 * error
        if e2 >= dy then
          if x0 == b.X then
            break
          end
          error = error + dy
          x0 = x0 + sx
        end

        if e2 <= dx then
          if y0 == b.Y then
            break
          end

          error = error + dx
          y0 = y0 + sy
        end
      end

      return line
    end
    return {
      GetPath = GetPath
    }
  end)
end)
