-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)
  namespace.class("CandidateInfo", function (namespace)
    local __ctor__
    __ctor__ = function (this, covered)
      this.Covered = covered
    end
    return {
      EntityDistance = 0,
      __ctor__ = __ctor__
    }
  end)
end)
