-- Generated by CSharp.lua Compiler
local System = System
local KnapcodeFactorioTools
local KnapcodeFactorioToolsData
local KnapcodeOilField
local ArrayIcon
System.import(function (out)
  KnapcodeFactorioTools = Knapcode.FactorioTools
  KnapcodeFactorioToolsData = Knapcode.FactorioTools.Data
  KnapcodeOilField = Knapcode.FactorioTools.OilField
  ArrayIcon = System.Array(KnapcodeFactorioToolsData.Icon)
end)
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)
  namespace.class("CleanBlueprint", function (namespace)
    local Execute
    Execute = function (blueprint)
      local context = KnapcodeOilField.InitializeContext.Execute(KnapcodeOilField.OilFieldOptions(), blueprint, KnapcodeOilField.TableArray.Empty(KnapcodeOilField.AvoidLocation))

      local entities = KnapcodeOilField.TableArray.New(KnapcodeFactorioToolsData.Entity)

      for i = 0, context.Centers:getCount() - 1 do
        local center = context.Centers:get(i)

        -- Pumpjacks are given a direction that doesn't overlap with another pumpjack, preferring the direction
        -- starting at the top then proceeding clockwise.
        local terminal = KnapcodeFactorioTools.CollectionExtensions.MinBy(context.CenterToTerminals:get(center):EnumerateItems(), function (x)
          return x.Direction
        end, KnapcodeOilField.TerminalLocation, System.Int32)

        local default = KnapcodeFactorioToolsData.Entity()
        default.EntityNumber = entities:getCount() + 1
        default.Direction = terminal.Direction
        default.Name = "pumpjack" --[[Vanilla.Pumpjack]]
        local extern = KnapcodeFactorioToolsData.Position()
        extern.X = center.X
        extern.Y = center.Y
        default.Position = extern
        entities:Add(default)
      end

      local default = KnapcodeFactorioToolsData.Blueprint()
      default.Entities = KnapcodeFactorioTools.CollectionExtensions.ToArray(entities, KnapcodeFactorioToolsData.Entity)
      local extern = KnapcodeFactorioToolsData.Icon()
      extern.Index = 1
      local ref = KnapcodeFactorioToolsData.SignalID()
      ref.Name = "pumpjack" --[[Vanilla.Pumpjack]]
      ref.Type = "item" --[[Vanilla.Item]]
      extern.Signal = ref
      default.Icons = ArrayIcon(1, { extern })
      default.Item = "blueprint" --[[Vanilla.Blueprint]]
      default.Version = 0
      return default
    end
    return {
      Execute = Execute
    }
  end)
end)
