-- Generated by CSharp.lua Compiler
local System = System
local KnapcodeOilField
System.import(function (out)
  KnapcodeOilField = Knapcode.FactorioTools.OilField
end)
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)
  namespace.class("Context", function (namespace)
    local GetLocationDictionary, GetLocationDictionary1, GetLocationSet, GetLocationSet1, GetLocationSet2, GetLocationSet3, GetLocationSet4, GetLocationSet5, 
    GetLocationSet6, GetLocationSet7, GetLocationSet8, GetSingleLocationSet
    GetLocationDictionary = function (this, T)
      return KnapcodeOilField.LocationIntDictionary_1(T)(this.Grid.Width)
    end
    GetLocationDictionary1 = function (this, capacity, T)
      return System.new(KnapcodeOilField.LocationIntDictionary_1(T), 2, this.Grid.Width, capacity)
    end
    GetLocationSet = function (this, other)
      local enumerateSet = other
      if System.is(enumerateSet, KnapcodeOilField.LocationIntSet) then
        return KnapcodeOilField.LocationIntSet(enumerateSet)
      end


      local singleSet = other
      if System.is(singleSet, KnapcodeOilField.SingleLocationSet) then
        return System.new(KnapcodeOilField.SingleLocationSet, 2, singleSet)
      end

      return KnapcodeOilField.LocationBitSet(System.cast(KnapcodeOilField.LocationBitSet, other))
    end
    GetLocationSet1 = function (this)
      return GetLocationSet2(this, false)
    end
    GetLocationSet2 = function (this, allowEnumerate)
      return allowEnumerate and System.new(KnapcodeOilField.LocationIntSet, 2, this.Grid.Width) or System.new(KnapcodeOilField.LocationBitSet, 2, this.Grid.Width, this.Grid.Height)
    end
    GetLocationSet3 = function (this, location)
      return GetLocationSet4(this, location, false)
    end
    GetLocationSet4 = function (this, location, allowEnumerate)
      local set = GetLocationSet2(this, allowEnumerate)
      set:Add(location)
      return set
    end
    GetLocationSet5 = function (this, capacity)
      return GetLocationSet6(this, capacity, false)
    end
    GetLocationSet6 = function (this, capacity, allowEnumerate)
      return allowEnumerate and System.new(KnapcodeOilField.LocationIntSet, 3, this.Grid.Width, capacity) or System.new(KnapcodeOilField.LocationBitSet, 2, this.Grid.Width, this.Grid.Height)
    end
    GetLocationSet7 = function (this, location, capacity)
      return GetLocationSet8(this, location, capacity, false)
    end
    GetLocationSet8 = function (this, location, capacity, allowEnumerate)
      local set = GetLocationSet6(this, capacity, allowEnumerate)
      set:Add(location)
      return set
    end
    GetSingleLocationSet = function (this, location)
      return System.new(KnapcodeOilField.SingleLocationSet, 3, location)
    end
    return {
      DeltaX = 0,
      DeltaY = 0,
      GetLocationDictionary = GetLocationDictionary,
      GetLocationDictionary1 = GetLocationDictionary1,
      GetLocationSet = GetLocationSet,
      GetLocationSet1 = GetLocationSet1,
      GetLocationSet2 = GetLocationSet2,
      GetLocationSet3 = GetLocationSet3,
      GetLocationSet4 = GetLocationSet4,
      GetLocationSet5 = GetLocationSet5,
      GetLocationSet6 = GetLocationSet6,
      GetLocationSet7 = GetLocationSet7,
      GetLocationSet8 = GetLocationSet8,
      GetSingleLocationSet = GetSingleLocationSet
    }
  end)
end)
