-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)
  namespace.class("Endpoints", function (namespace)
    local __ctor__
    __ctor__ = function (this, a, b)
      this.A = a
      this.B = b
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
