-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.Data", function (namespace)
  namespace.class("Entity", function (namespace)
    local __ctor__
    __ctor__ = function (this)
      this.Position = nil
    end
    return {
      EntityNumber = 0,
      Name = nil,
      __ctor__ = __ctor__
    }
  end)
end)
