-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.Data", function (namespace)
  namespace.class("EntityNames", function (namespace)
    namespace.class("Vanilla", function (namespace)
      return {}
    end)
    namespace.class("AaiIndustry", function (namespace)
      return {}
    end)
    return {}
  end)
end)
