-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.Data", function (namespace)
  namespace.class("Icon", function (namespace)
    local __ctor__
    __ctor__ = function (this)
      this.Signal = nil
    end
    return {
      Index = 0,
      __ctor__ = __ctor__
    }
  end)
end)
