-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)
  namespace.interface("ILocationSet", function ()
    return {}
  end)
end)
