-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)
  namespace.interface("ITableArray_1", function ()
    return function (T)
      return {
        base = function (out)
          return {
            out.Knapcode.FactorioTools.OilField.IReadOnlyTableArray_1(T)
          }
        end
      }
    end
  end)
end)
