-- Generated by CSharp.lua Compiler
local System = System
local KnapcodeOilField
System.import(function (out)
  KnapcodeOilField = Knapcode.FactorioTools.OilField
end)
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)
  namespace.class("Pipe", function (namespace)
    local getLabel, __ctor__
    __ctor__ = function (this, id)
      KnapcodeOilField.GridEntity.__ctor__(this, id)
    end
    getLabel = function (this)
      return "o"
    end
    return {
      base = function (out)
        return {
          out.Knapcode.FactorioTools.OilField.GridEntity
        }
      end,
      getLabel = getLabel,
      __ctor__ = __ctor__
    }
  end)
end)
