-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.Data", function (namespace)
  namespace.class("Position", function (namespace)
    return {
      X = 0,
      Y = 0
    }
  end)
end)
