-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.Data", function (namespace)
  namespace.class("SignalID", function (namespace)
    return {
      Name = nil,
      Type = nil
    }
  end)
end)
