-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)
  namespace.class("UndergroundPipe", function (namespace)
    local getLabel, __ctor__
    __ctor__ = function (this, id, direction)
      System.base(this).__ctor__(this, id)
      this.Direction = direction
    end
    getLabel = function (this)
      local default
      local extern = this.Direction
      if extern == 0 --[[Direction.Up]] then
        default = "^"
      elseif extern == 2 --[[Direction.Right]] then
        default = ">"
      elseif extern == 4 --[[Direction.Down]] then
        default = "v"
      elseif extern == 6 --[[Direction.Left]] then
        default = "<"
      else
        default = System.throw(System.NotImplementedException())
      end
      return default
    end
    return {
      base = function (out)
        return {
          out.Knapcode.FactorioTools.OilField.Pipe
        }
      end,
      Direction = 0,
      getLabel = getLabel,
      __ctor__ = __ctor__
    }
  end)
end)
