-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FluteSharp", function (namespace)
  namespace.struct("Branch", function (namespace)
    local EqualsObj, Equals, GetHashCode, op_Equality, op_Inequality, class
    EqualsObj = function (this, obj)
      local branch = obj
      return System.is(branch, class) and Equals(this, branch:__clone__())
    end
    Equals = function (this, other)
      return this.X == other.X and this.Y == other.Y and this.N == other.N
    end
    GetHashCode = function (this)
      return System.HashCode.Combine(this.X, this.Y, this.N, System.Int32, System.Int32, System.Int32)
    end
    op_Equality = function (left, right)
      return Equals(left, right:__clone__())
    end
    op_Inequality = function (left, right)
      return not (op_Equality(left, right))
    end
    class = {
      base = function (out)
        return {
          System.IEquatable_1(out.Knapcode.FluteSharp.Branch)
        }
      end,
      X = 0,
      Y = 0,
      N = 0,
      EqualsObj = EqualsObj,
      Equals = Equals,
      GetHashCode = GetHashCode,
      op_Equality = op_Equality,
      op_Inequality = op_Inequality
    }
    return class
  end)
end)
