-- Generated by CSharp.lua Compiler
--[[ Source: https://home.engineering.iastate.edu/~cnchu/Flute.java
 * The Java-based implementation of the LUT reader is by Stefan Mücke. Only the LUT reader is copied from his Java implementation and ported to C#.
 ]]
local System = System
local ArrayByte = System.Array(System.Byte)
System.namespace("Knapcode.FluteSharp", function (namespace)
  namespace.class("Csoln", function (namespace)
    local __ctor__
    __ctor__ = function (this, d)
      this.seg = ArrayByte(11)
      this.rowcol = ArrayByte(d - 2)
      this.neighbor = ArrayByte(2 * d - 2)
    end
    return {
      parent = 0,
      __ctor__ = __ctor__
    }
  end)
end)
