-- Generated by CSharp.lua Compiler
return function (path)
  return System.init({
    path = path,
    files = {
      "Branch",
      "Csoln",
      "FLUTE",
      "LookUpTable_Degree6_g",
      "Point",
      "Tree"
    },
    types = {
      "Knapcode.FluteSharp.LookUpTable",
      "Knapcode.FluteSharp.Branch",
      "Knapcode.FluteSharp.Csoln",
      "Knapcode.FluteSharp.FLUTE",
      "Knapcode.FluteSharp.LookUpTable.ByteReader",
      "Knapcode.FluteSharp.Point",
      "Knapcode.FluteSharp.Tree"
    }
  })
end
