name: Continuous integration

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

env:
  BUILD_PATH: "./src/vue"

jobs:
  build-pages:
    name: Build pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Restore dependencies
        run: npm install
        working-directory: ${{ env.BUILD_PATH }}
        
      - name: Build
        run: npm run build
        working-directory: ${{ env.BUILD_PATH }}
        env:
          BASE_PATH: '${{ steps.pages.outputs.base_path }}'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '${{ env.BUILD_PATH }}/dist'

  build-dotnet:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
        
      - name: Restore workloads
        run: dotnet workload restore
        
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build debug
        run: dotnet build --configuration Debug
    
      - name: Test
        run: dotnet test --no-build
      
      - name: Build release
        run: dotnet build --configuration Release

      - name: Publish for Windows
        run: dotnet publish src/WebApp --configuration Release --output src/WebApp/bin/Release/publish --runtime win-x64 --no-self-contained /p:PublishReadyToRun=true
