name: Deploy tag to Vercel

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    name: Trigger deploy hook
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d {} $DEPLOY_HOOK
        env:
          DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_TAGS_DEPLOY_HOOK }}
